[package]
name = "spuristo"
authors = ["LBlend <lblend@protonmail.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
bluer = "0.13.0"
chrono = "0.4"
futures = "0.3"
job_scheduler = "1.2.1"
tokio = { version = "1.12.0", features = ["full"] }
structopt = "0.3.25"